services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cisco
    networks:
      - keycloak-network
  keycloak:

    image: jboss/keycloak:16.1.1
    ports:
      - 8180:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: cisco
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminpass
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/standalone/configuration/realm-export.json
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/standalone/configuration/realm-export.json
    networks:
      - keycloak-network
    depends_on:
      - postgres

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
